"""Live customer lookup against the EasyWeek workspace (preparation stage).

Why this exists next to :mod:`customers`
----------------------------------------
:mod:`customers` resolves a customer from an operator's file export, because when
PR-11.1 was written no customer endpoint was confirmed. Three are confirmed now:

* ``GET  /api/public/v2/customers``                — filtered list
* ``GET  /api/public/v2/customers/{customer_uuid}`` — one card
* ``POST /api/public/v2/customers``                — create

That does not retire the export. The export stays the artefact the *apply* path
reads, so a bulk run is not one lookup per booking against a live API. What this
module changes is where the export comes from: the preparation stage builds it
from the live workspace instead of from a spreadsheet an operator regenerated by
hand, which is where most of the several hours went.

What "not found" is allowed to mean
-----------------------------------
Only one thing: the workspace was read completely and holds no card with this
number. Every other unhappy ending is :data:`LOOKUP_UNDETERMINED` — an auth
failure, a timeout, a malformed page, a page count that does not add up, a
response whose rows do not actually carry the number that was asked for. The
distinction is the whole point of the module: "absent" is the one outcome that
authorises a ``POST``, and a customer created because the API was briefly
unreachable is a duplicate card sitting on top of somebody's visit history.

Customers are WORKSPACE-scoped
------------------------------
The customer object carries no location field, and the same person is reachable
from Durlach, Karlsruhe and Rastatt alike. Nothing here filters by branch. A
lookup that came back empty has said something about the workspace, not about a
branch — and a lookup restricted to one branch would say nothing at all.

PII in the URL
--------------
``phone`` is a query parameter, so the number reaches the one place a log line is
written without anybody deciding to write it. :func:`silence_http_request_logs`
closes that off before the first request, and :class:`PhoneQueryLogFilter` scrubs
the parameter even if something re-enables the logger later. Our own log lines
carry :func:`phone_fingerprint` — enough to correlate two lines, not enough to
call anyone.
"""

from __future__ import annotations

import hashlib
import logging
import re
from dataclasses import dataclass
from typing import Any, Final, Protocol

from altegio_bot.easyweek_migration.customers import (
    CustomerCard,
    normalized_international_phone,
)
from altegio_bot.easyweek_migration.manifest import canonical_uuid
from altegio_bot.easyweek_migration.write_client import (
    EasyWeekAuthError,
    EasyWeekError,
    EasyWeekNotFoundError,
)

logger = logging.getLogger(__name__)

# Outcomes. Exactly one per lookup, and only ABSENT authorises a creation.
LOOKUP_FOUND: Final = "customer_found"
LOOKUP_ABSENT: Final = "customer_absent"
LOOKUP_AMBIGUOUS: Final = "customer_ambiguous"
LOOKUP_PHONE_UNUSABLE: Final = "customer_phone_unusable"
LOOKUP_FIRST_NAME_MISSING: Final = "customer_first_name_missing"
LOOKUP_UNDETERMINED: Final = "customer_lookup_undetermined"

# Why a lookup is undetermined. Stable codes, safe to log and to report.
DETAIL_ACCESS_DENIED: Final = "lookup_access_denied"
DETAIL_TRANSPORT: Final = "lookup_transport_error"
DETAIL_MALFORMED: Final = "lookup_response_malformed"
DETAIL_PAGINATION_INCOMPLETE: Final = "lookup_pagination_incomplete"
DETAIL_PAGINATION_UNBOUNDED: Final = "lookup_pagination_unbounded"
# The server returned rows that do not carry the number we filtered on. Either
# the filter is not the exact match the documentation states, or we are reading
# somebody else's page. Both mean the answer proves nothing.
DETAIL_FILTER_UNVERIFIED: Final = "lookup_filter_unverified"

# A single phone cannot legitimately span this many pages of 100. Reaching it
# means the filter is not filtering, and walking further would only spend the
# rate budget on it.
_MAX_PAGES: Final = 20

_PHONE_QUERY_RE: Final = re.compile(r"((?:phone|email)=)[^&\s\"']+", re.IGNORECASE)


class SupportsCustomerReads(Protocol):
    """The slice of the migration write client this module reads through."""

    async def list_customers(self, *, params: dict[str, Any]) -> dict[str, Any]: ...

    async def get_customer(self, customer_uuid: str) -> dict[str, Any]: ...


# ---------------------------------------------------------------------------
# Keeping phone numbers out of the logs
# ---------------------------------------------------------------------------


class PhoneQueryLogFilter(logging.Filter):
    """Scrub ``phone=`` / ``email=`` out of any record that carries a URL.

    Belt and braces next to :func:`silence_http_request_logs`: that lifts the
    level, this survives somebody lowering it again — a ``-v`` flag, a debug
    session, a library that configures logging on import.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        try:
            message = record.getMessage()
        except Exception:  # pragma: no cover - a broken record must not block the run
            return True
        if "phone=" not in message and "email=" not in message:
            return True
        record.msg = _PHONE_QUERY_RE.sub(r"\1<redacted>", message)
        record.args = ()
        return True


def silence_http_request_logs() -> None:
    """Raise the HTTP loggers to WARNING and attach the scrubbing filter.

    ``httpx`` logs one INFO line per request containing the full URL, and this
    stage's URLs contain ``?phone=%2B49...``. The stage's own progress lines are
    written by us, at our own level; nothing is lost by taking the request lines
    away, and a phone number in a container log is not something that can be
    taken back.
    """
    scrubber = PhoneQueryLogFilter()
    for name in ("httpx", "httpcore", "httpx._client"):
        target = logging.getLogger(name)
        if target.level < logging.WARNING:
            target.setLevel(logging.WARNING)
        if not any(isinstance(existing, PhoneQueryLogFilter) for existing in target.filters):
            target.addFilter(scrubber)


def phone_fingerprint(phone: str) -> str:
    """A stable, non-reversible tag for one number, for logs and reports.

    Two lines about the same customer can be tied together; no line can be tied
    to a person. Deliberately not a prefix/suffix mask: a German mobile masked to
    ``+49...4321`` is still identifying inside one salon's customer base.
    """
    return hashlib.sha256(phone.encode("utf-8")).hexdigest()[:12]


# ---------------------------------------------------------------------------
# Reading one response
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CustomerLookup:
    """One resolution attempt against the live workspace."""

    phone: str | None
    outcome: str
    uuid: str | None = None
    card: CustomerCard | None = None
    match_count: int = 0
    detail: str | None = None

    @property
    def found(self) -> bool:
        return self.outcome == LOOKUP_FOUND

    @property
    def creatable(self) -> bool:
        """Only a proven absence authorises a ``POST``."""
        return self.outcome == LOOKUP_ABSENT

    def as_safe_dict(self) -> dict[str, Any]:
        """Log/report shape. No number, no name — a fingerprint and a code."""
        return {
            "phone": phone_fingerprint(self.phone) if self.phone else None,
            "outcome": self.outcome,
            "customer_uuid": self.uuid,
            "match_count": self.match_count,
            "detail": self.detail,
        }


class CustomerLookupUndetermined(Exception):
    """Raised internally to carry a stable detail code out of a page read."""

    def __init__(self, detail: str) -> None:
        super().__init__(detail)
        self.detail = detail


def _read_pagination(meta: object, *, page: int) -> tuple[int, int]:
    """``(last_page, total)`` from a response envelope, or refuse.

    Deliberately not reusing the catalogue reader: identical strictness, but the
    codes an operator sees have to say which read was incomplete. A missing or
    non-integer field is malformed rather than "assume one page" — assuming one
    page is exactly how a second page holding the real customer gets skipped and
    the answer becomes a wrong "absent".
    """
    if not isinstance(meta, dict):
        raise CustomerLookupUndetermined(DETAIL_MALFORMED)

    def _int(key: str) -> int:
        value = meta.get(key)
        if isinstance(value, bool) or not isinstance(value, int):
            raise CustomerLookupUndetermined(DETAIL_MALFORMED)
        return value

    current_page = _int("current_page")
    last_page = _int("last_page")
    total = _int("total")
    if current_page != page:
        # The server answered a different page than the one asked for. Merging
        # it into the accumulator would double-count or skip.
        raise CustomerLookupUndetermined(DETAIL_PAGINATION_INCOMPLETE)
    if last_page < 1 or total < 0:
        raise CustomerLookupUndetermined(DETAIL_MALFORMED)
    return last_page, total


def read_customer_card(payload: object, *, expected_phone: str | None = None) -> CustomerCard:
    """One customer object → a card, verifying rather than trusting.

    ``expected_phone`` is checked when given: a 200 is not proof that the row
    belongs to the number we asked about.
    """
    if not isinstance(payload, dict):
        raise CustomerLookupUndetermined(DETAIL_MALFORMED)

    customer_uuid = canonical_uuid(payload.get("uuid") or payload.get("id"))
    if customer_uuid is None:
        raise CustomerLookupUndetermined(DETAIL_MALFORMED)

    phone = normalized_international_phone(payload.get("phone"))
    if phone is None:
        # A card we cannot read the number of cannot be proven to be this
        # customer's, and cannot be used to prove one absent either.
        raise CustomerLookupUndetermined(DETAIL_FILTER_UNVERIFIED)
    if expected_phone is not None and phone != expected_phone:
        raise CustomerLookupUndetermined(DETAIL_FILTER_UNVERIFIED)

    raw_first = payload.get("first_name")
    first_name = " ".join(raw_first.split()) if isinstance(raw_first, str) else None
    return CustomerCard(uuid=customer_uuid, phone=phone, first_name=first_name or None)


def _rows(payload: dict[str, Any]) -> list[Any]:
    data = payload.get("data")
    if not isinstance(data, list):
        raise CustomerLookupUndetermined(DETAIL_MALFORMED)
    return data


# ---------------------------------------------------------------------------
# The lookup
# ---------------------------------------------------------------------------


async def lookup_customer_by_phone(client: SupportsCustomerReads, raw_phone: object) -> CustomerLookup:
    """Resolve one number against the whole workspace, or say why it could not.

    Never narrowed to a branch, never widened to a name: a name match is not
    evidence of identity, and quietly matching on e-mail instead would answer a
    different question than the one the caller asked.
    """
    phone = normalized_international_phone(raw_phone)
    if phone is None:
        return CustomerLookup(phone=None, outcome=LOOKUP_PHONE_UNUSABLE)

    cards: dict[str, CustomerCard] = {}
    rows_seen = 0
    try:
        page = 1
        while True:
            if page > _MAX_PAGES:
                raise CustomerLookupUndetermined(DETAIL_PAGINATION_UNBOUNDED)
            payload = await client.list_customers(params={"phone": phone, "page": page})
            last_page, total = _read_pagination(payload.get("meta"), page=page)
            for row in _rows(payload):
                rows_seen += 1
                card = read_customer_card(row, expected_phone=phone)
                # The same uuid listed twice is one customer, as in `customers`.
                cards.setdefault(card.uuid, card)
            if page >= last_page:
                if rows_seen < total:
                    # The server counted rows it did not hand over. That is an
                    # unfinished read, and an unfinished read is not an absence —
                    # the row we never saw may be the customer.
                    raise CustomerLookupUndetermined(DETAIL_PAGINATION_INCOMPLETE)
                break
            page += 1
    except CustomerLookupUndetermined as undetermined:
        return CustomerLookup(phone=phone, outcome=LOOKUP_UNDETERMINED, detail=undetermined.detail)
    except EasyWeekAuthError:
        return CustomerLookup(phone=phone, outcome=LOOKUP_UNDETERMINED, detail=DETAIL_ACCESS_DENIED)
    except EasyWeekError:
        # Every remaining client failure — timeout, 5xx, protocol, exhausted
        # retries. None of them has read the workspace.
        return CustomerLookup(phone=phone, outcome=LOOKUP_UNDETERMINED, detail=DETAIL_TRANSPORT)

    if not cards:
        return CustomerLookup(phone=phone, outcome=LOOKUP_ABSENT)
    if len(cards) > 1:
        # Two cards on one number: a couple, a family phone, a duplicated import.
        # Not something to auto-merge and not something to pick a winner from.
        return CustomerLookup(phone=phone, outcome=LOOKUP_AMBIGUOUS, match_count=len(cards))

    card = next(iter(cards.values()))
    if not card.addressable:
        return CustomerLookup(
            phone=phone,
            outcome=LOOKUP_FIRST_NAME_MISSING,
            uuid=card.uuid,
            card=card,
            match_count=1,
        )
    return CustomerLookup(phone=phone, outcome=LOOKUP_FOUND, uuid=card.uuid, card=card, match_count=1)


async def verify_customer(client: SupportsCustomerReads, customer_uuid: str, *, expected_phone: str) -> CustomerCard:
    """``GET /customers/{uuid}`` after a creation, and check what came back.

    The ``POST`` response is the server describing its own intent; this is the
    workspace. Raises :class:`CustomerLookupUndetermined` when the card cannot be
    read or does not carry the expected number, so a caller cannot record a
    creation it has not seen.
    """
    canonical = canonical_uuid(customer_uuid)
    if canonical is None:
        raise CustomerLookupUndetermined(DETAIL_MALFORMED)
    try:
        payload = await client.get_customer(canonical)
    except EasyWeekNotFoundError:
        raise CustomerLookupUndetermined(DETAIL_MALFORMED) from None
    except EasyWeekAuthError:
        raise CustomerLookupUndetermined(DETAIL_ACCESS_DENIED) from None
    except EasyWeekError:
        raise CustomerLookupUndetermined(DETAIL_TRANSPORT) from None

    body = payload.get("data") if isinstance(payload.get("data"), dict) else payload
    card = read_customer_card(body, expected_phone=expected_phone)
    if card.uuid != canonical:
        raise CustomerLookupUndetermined(DETAIL_FILTER_UNVERIFIED)
    return card
