"""add whatsapp_senders and service_sender_rules

Revision ID: 16ffb80bd379
Revises: aa0be6363e16
Create Date: 2026-02-03 18:28:43.601387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ffb80bd379'
down_revision: Union[str, Sequence[str], None] = 'aa0be6363e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_sender_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('sender_code', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'service_id', name='uq_service_sender_rules_company_service')
    )
    op.create_index(op.f('ix_service_sender_rules_company_id'), 'service_sender_rules', ['company_id'], unique=False)
    op.create_index(op.f('ix_service_sender_rules_service_id'), 'service_sender_rules', ['service_id'], unique=False)
    op.create_table('whatsapp_senders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sender_code', sa.String(length=32), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('display_phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sender_code', name='uq_whatsapp_senders_company_code')
    )
    op.create_index(op.f('ix_whatsapp_senders_company_id'), 'whatsapp_senders', ['company_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_senders_sender_code'), 'whatsapp_senders', ['sender_code'], unique=False)
    op.add_column('outbox_messages', sa.Column('sender_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_outbox_messages_sender_id'), 'outbox_messages', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'outbox_messages', 'whatsapp_senders', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outbox_messages', type_='foreignkey')
    op.drop_index(op.f('ix_outbox_messages_sender_id'), table_name='outbox_messages')
    op.drop_column('outbox_messages', 'sender_id')
    op.drop_index(op.f('ix_whatsapp_senders_sender_code'), table_name='whatsapp_senders')
    op.drop_index(op.f('ix_whatsapp_senders_company_id'), table_name='whatsapp_senders')
    op.drop_table('whatsapp_senders')
    op.drop_index(op.f('ix_service_sender_rules_service_id'), table_name='service_sender_rules')
    op.drop_index(op.f('ix_service_sender_rules_company_id'), table_name='service_sender_rules')
    op.drop_table('service_sender_rules')
    # ### end Alembic commands ###
