"""add clients records record_services

Revision ID: 195f3116bdca
Revises: aef7d5e35640
Create Date: 2026-01-21 16:58:40.380263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '195f3116bdca'
down_revision: Union[str, Sequence[str], None] = 'aef7d5e35640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('altegio_client_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_e164', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'altegio_client_id', name='uq_clients_company_altegio_id')
    )
    op.create_index(op.f('ix_clients_altegio_client_id'), 'clients', ['altegio_client_id'], unique=False)
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.create_index(op.f('ix_clients_phone_e164'), 'clients', ['phone_e164'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('altegio_record_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('altegio_client_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('staff_name', sa.String(length=256), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('short_link', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('visit_attendance', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'altegio_record_id', name='uq_records_company_altegio_id')
    )
    op.create_index(op.f('ix_records_altegio_client_id'), 'records', ['altegio_client_id'], unique=False)
    op.create_index(op.f('ix_records_altegio_record_id'), 'records', ['altegio_record_id'], unique=False)
    op.create_index(op.f('ix_records_client_id'), 'records', ['client_id'], unique=False)
    op.create_index(op.f('ix_records_company_id'), 'records', ['company_id'], unique=False)
    op.create_index(op.f('ix_records_is_deleted'), 'records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_records_staff_id'), 'records', ['staff_id'], unique=False)
    op.create_index(op.f('ix_records_starts_at'), 'records', ['starts_at'], unique=False)
    op.create_table('record_services',
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('cost_to_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_services')
    op.drop_index(op.f('ix_records_starts_at'), table_name='records')
    op.drop_index(op.f('ix_records_staff_id'), table_name='records')
    op.drop_index(op.f('ix_records_is_deleted'), table_name='records')
    op.drop_index(op.f('ix_records_company_id'), table_name='records')
    op.drop_index(op.f('ix_records_client_id'), table_name='records')
    op.drop_index(op.f('ix_records_altegio_record_id'), table_name='records')
    op.drop_index(op.f('ix_records_altegio_client_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_clients_phone_e164'), table_name='clients')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_altegio_client_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
