"""add messaging tables

Revision ID: aa0be6363e16
Revises: 195f3116bdca
Create Date: 2026-01-21 18:25:13.523498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa0be6363e16'
down_revision: Union[str, Sequence[str], None] = '195f3116bdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_rate_limits',
    sa.Column('phone_e164', sa.String(length=32), nullable=False),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('phone_e164')
    )
    op.create_index(op.f('ix_contact_rate_limits_next_allowed_at'), 'contact_rate_limits', ['next_allowed_at'], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_code'), 'message_templates', ['code'], unique=False)
    op.create_index(op.f('ix_message_templates_company_id'), 'message_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_templates_is_active'), 'message_templates', ['is_active'], unique=False)
    op.create_table('message_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_jobs_client_id'), 'message_jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_message_jobs_company_id'), 'message_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_jobs_dedupe_key'), 'message_jobs', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_message_jobs_job_type'), 'message_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_message_jobs_record_id'), 'message_jobs', ['record_id'], unique=False)
    op.create_index(op.f('ix_message_jobs_run_at'), 'message_jobs', ['run_at'], unique=False)
    op.create_index(op.f('ix_message_jobs_status'), 'message_jobs', ['status'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('phone_e164', sa.String(length=32), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['message_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_messages_client_id'), 'outbox_messages', ['client_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_company_id'), 'outbox_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_job_id'), 'outbox_messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_phone_e164'), 'outbox_messages', ['phone_e164'], unique=False)
    op.create_index(op.f('ix_outbox_messages_provider_message_id'), 'outbox_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_record_id'), 'outbox_messages', ['record_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_scheduled_at'), 'outbox_messages', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_status'), 'outbox_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_messages_template_code'), 'outbox_messages', ['template_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_messages_template_code'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_status'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_scheduled_at'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_record_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_provider_message_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_phone_e164'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_job_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_company_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_client_id'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_message_jobs_status'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_run_at'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_record_id'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_job_type'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_dedupe_key'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_company_id'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_client_id'), table_name='message_jobs')
    op.drop_table('message_jobs')
    op.drop_index(op.f('ix_message_templates_is_active'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_company_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_code'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_contact_rate_limits_next_allowed_at'), table_name='contact_rate_limits')
    op.drop_table('contact_rate_limits')
    # ### end Alembic commands ###
