"""init

Revision ID: aef7d5e35640
Revises: 
Create Date: 2026-01-20 21:13:57.978367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aef7d5e35640'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('altegio_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('resource', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('event_status', sa.String(length=32), nullable=True),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_altegio_events_company_id'), 'altegio_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_altegio_events_dedupe_key'), 'altegio_events', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_altegio_events_event_status'), 'altegio_events', ['event_status'], unique=False)
    op.create_index(op.f('ix_altegio_events_resource'), 'altegio_events', ['resource'], unique=False)
    op.create_index(op.f('ix_altegio_events_resource_id'), 'altegio_events', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_altegio_events_resource_id'), table_name='altegio_events')
    op.drop_index(op.f('ix_altegio_events_resource'), table_name='altegio_events')
    op.drop_index(op.f('ix_altegio_events_event_status'), table_name='altegio_events')
    op.drop_index(op.f('ix_altegio_events_dedupe_key'), table_name='altegio_events')
    op.drop_index(op.f('ix_altegio_events_company_id'), table_name='altegio_events')
    op.drop_table('altegio_events')
    # ### end Alembic commands ###
