"""Required file policy: reject AI authorship signatures, not product mentions.

After the owner commits this test, changing or removing it (including its
patterns, sole exemption or CI coverage) requires explicit owner permission.
Fix an offending file instead of weakening this check to make CI pass.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
# Only this exact file contains intentional signatures as regression examples.
EXAMPLE_FILE = Path(__file__).resolve().relative_to(ROOT).as_posix()
AI_NAME = (
    r"(?:Claude(?:[ \t]+(?:Code|Opus|Sonnet|Haiku)(?:[ \t]+\d+(?:\.\d+)*)?)?"
    r"|Anthropic|(?:GitHub[ \t]+)?Copilot|OpenAI(?:[ \t]+(?:Codex|ChatGPT))?|ChatGPT|Codex)"
)
# Require an attribution phrase and an agent name ending at a delimiter.
# For example, a human named Claude Dupont must not match the name Claude.
SIGNATURE = re.compile(
    r"\b(?:co-authored-by[ \t]*:|(?:generated|written|created|authored)[ \t]+(?:by|with)"
    r"|(?:author|ai-assisted-by|assisted-by|generated-by)[ \t]*:)"
    r"[ \t]*\[?" + AI_NAME + r"(?=[ \t]*(?:$|[<\]\(\"'`.,!]|-->|\*/))"
    r"|\bco-authored-by[ \t]*:[^\r\n]*<"
    r"(?:noreply@(?:anthropic|openai)\.com|\d+\+copilot@users\.noreply\.github\.com)>",
    re.IGNORECASE,
)


def signature_locations(root: Path) -> list[str]:
    tracked = subprocess.check_output(["git", "-C", str(root), "ls-files", "-z"])
    findings = []
    for raw_path in tracked.split(b"\0"):
        if not raw_path:
            continue
        relative = raw_path.decode("utf-8", errors="surrogateescape")
        path = root / relative
        if relative == EXAMPLE_FILE or path.is_symlink() or not path.is_file():
            continue  # Deleted working-tree files and symlinks have no text to scan.
        content = path.read_bytes()
        if b"\0" in content:
            continue  # Binary assets are outside this text-file policy.
        for number, line in enumerate(content.decode("utf-8", errors="replace").splitlines(), 1):
            match = SIGNATURE.search(line)
            if match:
                findings.append(f"{relative}:{number}: {match.group(0)}")
    return findings


def test_tracked_files_have_no_ai_authorship_signatures():
    findings = signature_locations(ROOT)
    assert not findings, (
        "AI authorship signatures found; remove them from the listed files. "
        "Do not change this protected test without explicit owner permission:\n" + "\n".join(findings)
    )


@pytest.mark.parametrize(
    "line",
    [
        "# Generated with Claude Code",
        "// Written by GitHub Copilot",
        "<!-- Created by ChatGPT -->",
        "/* Authored by OpenAI Codex */",
        "🤖 Generated with [Claude Code](https://example.invalid)",
        "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
        "Co-authored-by: model <noreply@anthropic.com>",
        "Co-authored-by: assistant <198982749+Copilot@users.noreply.github.com>",
        "# Author: ChatGPT",
        "# generated by openai",
    ],
)
def test_signatures_are_rejected(line):
    assert SIGNATURE.search(line)


@pytest.mark.parametrize(
    "line",
    [
        "OPENAI_API_KEY = config.get('OPENAI_API_KEY')",
        "Compare Anthropic and OpenAI API responses.",
        "CLAUDE.md",
        "# Generated by Alembic",
        "# Generated by OpenAPI Generator",
        "Co-Authored-By: Jean-Claude Dupont <jcd@example.org>",
        "Co-Authored-By: Claude Dupont <claude@example.org>",
        "Co-Authored-By: Devin Smith <devin@example.org>",
        "# Written by Claude Dupont",
    ],
)
def test_product_mentions_and_human_authorship_are_allowed(line):
    assert not SIGNATURE.search(line)


def test_scan_covers_tracked_code_docs_and_tests_with_only_one_exact_exemption(tmp_path):
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    paths = ["src/example.py", "docs/guide.md", "tests/example.py", ".github/example.yml", EXAMPLE_FILE]
    for name in paths:
        path = tmp_path / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("ordinary text\n# Generated with Claude Code\n", encoding="utf-8")
    (tmp_path / "asset.bin").write_bytes(b"\0binary")
    subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
    (tmp_path / "untracked.txt").write_text("Generated with Claude Code\n", encoding="utf-8")
    assert sorted(signature_locations(tmp_path)) == sorted(
        f"{name}:2: Generated with Claude Code" for name in paths if name != EXAMPLE_FILE
    )
